### ISSUE TITLE
About iOS 8.0 compatibility

### ISSUE THREAD

**Issue by shar0** [damboscolo/SwiftToast#12]
Here the error:

```
Class Unavailable:
UIStackView before iOS 9.0
SwiftToastView.xib
```

Can alternative xib to programmatically?

**Comment by damboscolo** [comment]
Sorry for the late response. 

I've choosen to use stack view because it automatically resizes the spacing between the text and image.
I could do without stack but it would give a little more work because I would have to manually take care of the constraints and customizations. 😕

If you still want to use it for previous iOS versions feel free to work on it and send me a PR.
